# Generated by Django 3.1.2 on 2020-11-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_auto_20201116_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='jumlah',
        ),
    ]
