# Generated by Django 3.1.2 on 2020-11-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0005_auto_20201120_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kelompok_id',
            new_name='kelompok',
        ),
    ]
